var data = {
	images: [
		{
			src: [""],
			thumbnail: "",
			title: "Placeholder Entry",
			artist: "Placeholder Entry",
			artist_url: null,
			art_url: null,
			desc: "Do not delete this. You can use this to set the order the tags show up in the dropdown.",
			date_str: "Beginning of Time",
			tags: [],
			hidden: true
		},
		{
			src: ["https://cdn.imgchest.com/files/yvdcw8jdxjy.png"],
			thumbnail: "https://cdn.imgchest.com/files/y8xcn9bknq4.png",
			title: "Jedi Ingrid by Xander Wolk",
			artist: "Xander Wolk",
			artist_url: "https://bsky.app/profile/xander-wolk.bsky.social",
			art_url: "https://bsky.app/profile/xander-wolk.bsky.social/post/3ll5speu2fc2x",
			desc: "Jedi Knight Ingrid Brandl Galatea reporting for duty",
			date_str: "March 24 2025",
			tags: ["ingrid", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7bwck8ll6l7.png"],
			thumbnail: "https://cdn.imgchest.com/files/4apc5njj9b4.png",
			title: "Jedi Ingrid by Eine",
			artist: "eine_dx",
			artist_url: "https://eine-dx.carrd.co/#",
			art_url: null,
			desc: "Jedi Ingrid is out of this world",
			date_str: "December 21 2024",
			tags: ["ingrid", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4jdcvmoob34.png"],
			thumbnail: "https://cdn.imgchest.com/files/7w6c2pjjr8y.png",
			title: "Jedi Ingrid Chibi",
			artist: "inkanii",
			artist_url: "https://inkanii.carrd.co/",
			art_url: null,
			desc: "A smol Jedi Ingy",
			date_str: "October 6 2021",
			tags: ["ingrid", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/yvdcw8mxapy.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/7ogcbjoag6y.jpg",
			title: "Founders of the Ashen Jedi",
			artist: "sierra117renner",
			artist_url: "https://bsky.app/profile/s117renner.bsky.social",
			art_url: "https://bsky.app/profile/s117renner.bsky.social/post/3lbxevxeijs2z",
			desc: "On this day, the Mandalorian Jedi Cavil would cross paths with Ingrid Brandl Galatea and a new Jedi Order was born...",
			date_str: "November 27 2024",
			tags: ["ingrid", "cavil", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7mmc9mpajj7.png"],
			thumbnail: "https://cdn.imgchest.com/files/7bwck856o67.png",
			title: "Tending Her Wounds",
			artist: "Yumilattea",
			artist_url: "https://bsky.app/profile/yumilattea.bsky.social",
			art_url: null,
			desc: "FE12 is easily my top 3 favorite Fire Emblem game and Kris is my new favorite Avatar. Upon going through the supports, my girlfriend and I found a new Rarepair",
			date_str: "May 6 2025",
			tags: ["kris", "navarre", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/49zc26d2vky.png"],
			thumbnail: "https://cdn.imgchest.com/files/7bwck85k237.png",
			title: "Lavai: Majin Walker",
			artist: "DamoBelmont",
			artist_url: "https://bsky.app/profile/damobelmont.bsky.social",
			art_url: "https://bsky.app/profile/damobelmont.bsky.social/post/3liagjvckqc25",
			desc: "This was a gift commission of an OC from my friend Iris. She is the daughter of his OC and Camilla from Fates. Part of a FE/DMC/Yakuza crossover.",
			date_str: "February 12 2025",
			tags: ["oc", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/yrgcnv2r3j4.png"],
			thumbnail: "https://cdn.imgchest.com/files/739cx8vewa7.png",
			title: "Summoner Bune",
			artist: "cleru",
			artist_url: "https://bsky.app/profile/cleru.bsky.social",
			art_url: "https://bsky.app/profile/cleru.bsky.social/post/3lizdftkhss2v",
			desc: "Everyone's favorite lesbian grandma! This was a gift commission for Griff of her Summoner OC. Your wives are now forfeit.",
			date_str: "February 24 2025",
			tags: ["oc", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4jdcvmdwxw4.png"],
			thumbnail: "https://cdn.imgchest.com/files/4jdcvmdwvw4.png",
			title: "Ready for Battle",
			artist: "Adricarra",
			artist_url: "https://adricarra.carrd.co/",
			art_url: "https://x.com/adricarraart/status/1495403990200291331",
			desc: "My second commission from Adricarra",
			date_str: "February 20 2022",
			tags: ["ingrid", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/y8xcn9rver4.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/4apc5nmq624.jpg",
			title: "Retro Three Hopes Jedi Ingrid",
			artist: "Kshatriya 666",
			artist_url: "https://x.com/Kshatriya_666_",
			art_url: "https://x.com/Kshatriya_666_/status/1530915995698593792",
			desc: "Jedi Ingrid in a retro anime style. Tried to mix things up with a Three Hopes variant with a different Lightsaber.",
			date_str: "May 29 2022",
			tags: ["ingrid", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7pjcq9e8z87.png"],
			thumbnail: "https://cdn.imgchest.com/files/7kzcagrod57.png",
			title: "In the Arms of the Songstress",
			artist: "Merchantress",
			artist_url: "https://merchantressart.carrd.co/#",
			art_url: null,
			desc: "Some wholesome summer Dorogrid. I ship these two to this very day regardless of the supports. They deserved better.",
			date_str: "April 15 2022",
			tags: ["ingrid", "dorothea", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/4jdcvmdbzo4.png"],
			thumbnail: "https://cdn.imgchest.com/files/yq9c38r6aj4.png",
			title: "Aayla the Ranger",
			artist: "Nobuzeus",
			artist_url: "https://bsky.app/profile/nobuzeus.bsky.social",
			art_url: null,
			desc: "Commission of my girlfriend's OC Aayla. A human Ranger with the ability to transform into a raven and transform objects into metal with her silver hair.",
			date_str: "April 24 2025",
			tags: ["oc", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7lxcpzb3867.png"],
			thumbnail: "https://cdn.imgchest.com/files/4jdcvmpz5j4.png",
			title: "Cavil Fadel: Mandalorian Jedi Wayseeker",
			artist: "Arktoons",
			artist_url: "https://bsky.app/profile/arktoons.bsky.social",
			art_url: null,
			desc: "I always wanted to make a Mandalorian Jedi since I was a child. Cavil is my sort of justification for why Jedi Ingrid and several other Star Wars crossovers exist. He explores various universes and recruits folks into his personal Order: The Ashen Jedi.",
			date_str: "November 10 2023",
			tags: ["cavil", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/y2pcknb9dx7.png"],
			thumbnail: "https://cdn.imgchest.com/files/7lxcpzbgrz7.png",
			title: "Putting the Force in Galeforce",
			artist: "Zet",
			artist_url: "https://bsky.app/profile/zetsumi.bsky.social",
			art_url: null,
			desc: "Morgan from Awakening as a Jedi. Felt pretty self explanatory as a sword/magic user. Married Tiki in my playthrough as you can see from the green hair and pointy ears.",
			date_str: "January 19 2024",
			tags: ["morgan", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/49zc26lew5y.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/7pjcq9jbrn7.jpg",
			title: "Jedi Eunie",
			artist: "Chascoby",
			artist_url: "https://bsky.app/profile/chascoby.bsky.social",
			art_url: null,
			desc: "The Bus as a Jedi! Quite fitting considering she learns a class with a double-bladed weapon and her High Entia origins. Her design is based off of Bastilla from Knights of the Old Republic.",
			date_str: "date unknown",
			tags: ["eunie", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/yrgcnvdwbg4.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/739cx8robm7.jpg",
			title: "Mythra and Ingrid fusion",
			artist: "Gzei",
			artist_url: "https://bsky.app/profile/gzeidraws.bsky.social",
			art_url: null,
			desc: "Two blonde waifus forged into one! Gzei did an amazing job combining both of their designs.",
			date_str: "December 5 2022",
			tags: ["ingrid", "mythra", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/ye3c2l5pm64.png"],
			thumbnail: "https://cdn.imgchest.com/files/4apc5n2daw4.png",
			title: "Battle Damaged Cavil",
			artist: "Griff",
			artist_url: "https://bsky.app/profile/renaisblade.bsky.social",
			art_url: "https://bsky.app/profile/renaisblade.bsky.social/post/3lg4j22gzv22i",
			desc: "Tis but a scratch",
			date_str: "January 19 2025",
			tags: ["cavil", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/46acq9m8p27.png"],
			thumbnail: "https://cdn.imgchest.com/files/739cx8dbj97.png",
			title: "Suffering from Aura Farming",
			artist: "Motoi",
			artist_url: "https://skeb.jp/@motoiwork",
			art_url: null,
			desc: "Aura Farming? A bad migrane? Missing Ingrid? Any are applicable tbh. A May the Fourth gift from Eeby",
			date_str: "May 4 2025",
			tags: ["cavil", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/ye3c2a29aw4.png"],
			thumbnail: "https://cdn.imgchest.com/files/4gdcx5x6584.png",
			title: "Blue Sea Lion",
			artist: "Kalycoris",
			artist_url: "https://x.com/kalycoris",
			art_url: "https://x.com/kalycoris/status/1613519543179137024",
			desc: "Ingrid's underwater treasure hunt is going swimmingly",
			date_str: "January 12 2023",
			tags: ["ingrid", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7mmc9v9d6m7.png"],
			thumbnail: "https://cdn.imgchest.com/files/7w6c2l2a35y.png",
			title: "Jedi Merrin",
			artist: "RedKite",
			artist_url: "https://x.com/RedKite333",
			art_url: "https://x.com/RedKite333/status/1759584111470207301",
			desc: "That's one cool Jedi. Merrin from Fire Emblem Engage wearing Merrin's outfit from Jedi Survivor in a custom color scheme with assets of FE!Merrin thrown in.",
			date_str: "February 19 2024",
			tags: ["merrin", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/yrgcngnp264.png", "https://cdn.imgchest.com/files/7w6c2l2adzy.png", "https://cdn.imgchest.com/files/4z9cvov6567.png", "https://cdn.imgchest.com/files/y8xcn3njoz4.png"],
			thumbnail: "https://cdn.imgchest.com/files/49zc2w2q52y.png",
			title: "Jedi Ingrid FEH Edition",
			artist: "SilverCandyGum",
			artist_url: "https://bsky.app/profile/silvercandygum.bsky.social",
			art_url: "https://www.pixiv.net/en/artworks/106198597",
			desc: "Jedi Ingrid if she was a unit in Fire Emblem Heroes with attack, special and damage art",
			date_str: "March 13 2023",
			tags: ["ingrid", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/7lxcpnpkek7.png"],
			thumbnail: "https://cdn.imgchest.com/files/739cx9xapz7.png",
			title: "Jedi Ingrid as a FEH Sprite",
			artist: "Toto",
			artist_url: "https://bsky.app/profile/godlytoto.bsky.social",
			art_url: null,
			desc: "Jedi Ingrid if she was a sprite in Fire Emblem Heroes. Changed it up from her usual design with her longer hair and crossguard Lightsaber.",
			date_str: "September 2 2022",
			tags: ["ingrid", "sfw"],
			hidden: false
		},
		{
			src: ["https://cdn.imgchest.com/files/y8xcn3nb6n4.jpg"],
			thumbnail: "https://cdn.imgchest.com/files/46acqkqjdv7.jpg",
			title: "Biker Ingrid",
			artist: "Patdarux",
			artist_url: "https://x.com/patdarux",
			art_url: "https://x.com/patdarux/status/1448346168782725128",
			desc: "The Blue Shell is for Sylvain",
			date_str: "October 13 2021",
			tags: ["ingrid", "eechi"],
			hidden: false
		},
		{
			src: [""],
			thumbnail: "",
			title: "",
			artist: "",
			artist_url: "",
			art_url: "",
			desc: "",
			date_str: "",
			tags: [""],
			hidden: true
		}
	]
};
